version: '3'
services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend/chroma_db:/app/chroma_db
    environment:
      - CHROMA_PERSIST_DIR=/app/chroma_db
